### ISSUE TITLE
Añadir código INE en covid19-ccaa-spain_consolidated.csv 

### ISSUE THREAD

**Issue by bougar** [montera34/escovid19data#10]
Buenas tardes,
Antes de nada felicitar al administrador y a todos los colaboradores por este gran trabajo de ETL sobre los datos Covid-19 en España.
Revisando el fichero _covid19-ccaa-spain_consolidated.csv_, creo que sería una buena idea incluir el código INE de la comunidad autónoma para evitar problemas en el procesamiento de la cadena de texto del nombre de la comunidad y poder recurrir al código numérico con el cual es mucho más sencillo trabajar. Del mismo modo, creo que también sería útil añadir el código INE de la comunidad autónoma en el los datos consolidados por provincia.

Muchas gracias,
Un saludo.

**Comment by numeroteca** [comment]
Mira a ver si te funciona, ya está disponible el código del INE para cada comunidad autónoma.
