### ISSUE TITLE
Datos de Madrid

### ISSUE THREAD

**Issue by MariaN1966** [montera34/escovid19data#11]
Estaba comparando los datos de la IA de la comunidad de madrid que os salen a vosotros con los del ISCIII que publica en su cuadro de mando y no me coinciden. En primer lugar el dato de casos vosotros los dais de los de la comunidad de Madrid publica y no los "oficiales" del ISCIII. Quería saber si los datos que subís de Madrid los vais modificando con los datos que la comunidad corrige diariamente y vosotros que sabéis más ¿el ISCIII arregla las series de datos con los que va modificando la comunidad de madrid (que los va ajustando dia a dia según fecha de realización del pcr) o deja el dato estático?

**Comment by pirio72** [comment]
Hola, María:

Por un lado, hemos detectado que estábamos tomando los datos de publicación, cuando en realidad, los datos son siempre del día anterior. Eso ya está corregido.

Que yo sepa, supongo que tomamos cada día el número de casos. Tenemos justo pendiente revisar las actualizaciones de cada CCAA. 

Eso sí: como madrileño, me intrigaste... y el tema es mucho más complejo. 

De hecho, he realizado una cata al azar: he cogido el día **11 de agosto** y he comprobado que, desde entonces, en **todos y cada uno de los días posteriores hasta el último informe disponible (publicado el 7 de septiembre, con datos del **6 de septiembre**), el número de casos asignados al 11 de agosto ha ido aumentando (menos en un caso).

Es decir, casi un mes después, siguen asignando casos a ese día... ¿Por qué? ¿Ocurre sistemáticamente con todos los días? ¿Cuándo terminan de actualizar? ¿Reportan esos casos también al ISCIII?

**Comment by numeroteca** [comment]
Sí que corregimos las series. Los datos que usamos para la Comuniad de Madrid actualizan las series, de PCR al menos. Usamos como fuente elrepositorio que mantiene @alfonsotwr a partir de los datos publicados en PDF de la CM: https://github.com/alfonsotwr/snippets/blob/master/covidia-cam/madrid-series.csv 
Ayúdanos a completar la información en la wiki si algo no está claro: https://github.com/montera34/escovid19data/wiki#madrid

> ¿el ISCIII arregla las series de datos con los que va modificando la comunidad de madrid (que los va ajustando dia a dia según fecha de realización del pcr) o deja el dato estático?
Sí, corrige los datos cuando los publica. 
Decargamos el archivo original cuando se publica y como tenemos sistema de control de cambios con git puedes ver las diferencias.
* archivo RENAVE - ISCIII ne el repositorio https://code.montera34.com:4443/numeroteca/covid19/-/blob/master/data/original/spain/iscii_casos_renave.csv
* historial de cambios https://code.montera34.com:4443/numeroteca/covid19/-/commits/master/data/original/spain/iscii_casos_renave.csv

Usa el comando `git diff 3e3ac4ef6a60f 54eb4a69 data/original/spain/iscii_casos_renave.csv` para ver los cambios entre las últimas dos versiones (para eso tienes que haber clonado antes el otro repositorio https://code.montera34.com/numeroteca/covid19):
El resultado es algo como esto:
```
provincia_iso,fecha,num_casos,num_casos_prueba_pcr,num_casos_prueba_test_ac,num_casos_prueba_otras,num_casos_prueba_desconocida
-HU,2020-05-18,4,3,0,0,1
+HU,2020-05-18,5,3,0,0,2
```
Se modificaron los datos para el 18 de mayo 2020 en Huesca, pasaron los casos de 4 a 5.

Hay cambios a lo largo de todo el periodo, pero sobre todo en las úlitmas semanas.


![Screenshot from 2020-09-09 13-58-01](https://user-images.githubusercontent.com/1223722/92595353-851c3c80-f2a4-11ea-8aa7-0c0763c8ae44.png)
![Screenshot from 2020-09-09 13-57-17](https://user-images.githubusercontent.com/1223722/92595357-85b4d300-f2a4-11ea-842f-d63d83559950.png)

**Comment by MariaN1966** [comment]
Muchas gracias por la aclaración. Comparando la comunidad de Madrid en
datos de PCRs positivos en el pdf de la Comunidad y el dato de Renave no
cuadran nunca (eso ya pasa siempre y varias personas lo comentan en
twitter), ni siquiera el dato del nº de habitantes en la comunidad cuadra
entre la base que coge el ISCII (dato del INE a mediados de 2019) y el de
la Comunidad de Madrid que no lo dice (o al menos no lo he encontrado). En
fin, si consigo saber algo os lo comunico para la wiki. Y muchísimas
gracias por hacer accesibles los datos y traducir pdfs a csvs y todo el
código que hacéis público.

**Comment by pirio72** [comment]
Hola, María:

Mejor que Pablo, no te lo iba yo a explicar (estuve tentado). Solo añado un detalle: aunque no estoy metido con Madrid, sí me picó la curiosidad con tu mensaje. No es que los datos de ISCIII y de la Comunidad de Madrid no coincidan: es que los datos de casos de la Comunidad de Madrid, para un día concreto (pongamos, 11 de agosto) van aumentando.

Es decir: la Comunidad añade un histórico de casos al final de sus PDF. Si comparas, siguiendo el ejemplo, los datos del 11 de agosto que reportan el 12 de agosto (el "original", porque siempre reportan respecto al día anterior), y los datos de ese 11 de agosto en el histórico que aparece el 13 de agosto, y sucesivamente, verás que van cambiando hacia un valor mayor.

Más aún: en el **informe del 7 de septiembre**... esos datos del 11 de agosto siguen creciendo (??). Y es solo un ejemplo puntual, pero ¿habrá más? ;-)

Para investigar. Gracias a ti por tu interés.

**Comment by MariaN1966** [comment]
> Sí que corregimos las series. Los datos que usamos para la Comuniad de Madrid actualizan las series, de PCR al menos. Usamos como fuente elrepositorio que mantiene @alfonsotwr a partir de los datos publicados en PDF de la CM: https://github.com/alfonsotwr/snippets/blob/master/covidia-cam/madrid-series.csv
> Ayúdanos a completar la información en la wiki si algo no está claro: https://github.com/montera34/escovid19data/wiki#madrid
> 
> > ¿el ISCIII arregla las series de datos con los que va modificando la comunidad de madrid (que los va ajustando dia a dia según fecha de realización del pcr) o deja el dato estático?
> > Sí, corrige los datos cuando los publica.
> > Decargamos el archivo original cuando se publica y como tenemos sistema de control de cambios con git puedes ver las diferencias.
> 
> * archivo RENAVE - ISCIII ne el repositorio https://code.montera34.com:4443/numeroteca/covid19/-/blob/master/data/original/spain/iscii_casos_renave.csv
> * historial de cambios https://code.montera34.com:4443/numeroteca/covid19/-/commits/master/data/original/spain/iscii_casos_renave.csv
> 
> Usa el comando `git diff 3e3ac4ef6a60f 54eb4a69 data/original/spain/iscii_casos_renave.csv` para ver los cambios entre las últimas dos versiones (para eso tienes que haber clonado antes el otro repositorio https://code.montera34.com/numeroteca/covid19):
> El resultado es algo como esto:
> 
> ```
> provincia_iso,fecha,num_casos,num_casos_prueba_pcr,num_casos_prueba_test_ac,num_casos_prueba_otras,num_casos_prueba_desconocida
> -HU,2020-05-18,4,3,0,0,1
> +HU,2020-05-18,5,3,0,0,2
> ```
> 
> Se modificaron los datos para el 18 de mayo 2020 en Huesca, pasaron los casos de 4 a 5.
> 
> Hay cambios a lo largo de todo el periodo, pero sobre todo en las úlitmas semanas.
> 
> ![Screenshot from 2020-09-09 13-58-01](https://user-images.githubusercontent.com/1223722/92595353-851c3c80-f2a4-11ea-8aa7-0c0763c8ae44.png)
> ![Screenshot from 2020-09-09 13-57-17](https://user-images.githubusercontent.com/1223722/92595357-85b4d300-f2a4-11ea-842f-d63d83559950.png)

Hola, estoy viendo que los datos de RENAVE no se están actualizando en el fichero https://github.com/montera34/escovid19data/blob/master/data/output/covid19-provincias-spain_consolidated.xlsx. ¿lo estoy mirando mal? 
Gracias
