### ISSUE TITLE
Error Datos CCAA

### ISSUE THREAD

**Issue by daniclemente** [montera34/escovid19data#20]
Buenos días,

Se hicieron anoche modificaciones y hay un error en los datos del [CSV](https://raw.githubusercontent.com/montera34/escovid19data/master/data/output/covid19-ccaa-spain_consolidated.csv) y [XLSX](https://github.com/montera34/escovid19data/raw/master/data/output/covid19-ccaa-spain_consolidated.xlsx) de datos agregados por comunidades autónomas.

La tercera columna concatena fecha con nombre de la Comunidad:

```csv
"Andalucía",1,"2020-01-31Andalucía",2020-01-31,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0,0,0,0,0,8414240,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
```

Un saludo.

**Comment by numeroteca** [comment]
Gracias por informar. El error fue subsanado.
