### ISSUE TITLE
Error en columnas

### ISSUE THREAD

**Issue by enriquetomasmb** [montera34/escovid19data#22]
Muy buenas,

Os informo que tanto en los datos por CCAA como por provincias, la columna "intensive_care_per_1000000" (Casos UCI por 100.000 habitantes) debería de ser **"intensive_care_per_100000"** (le sobra un **0**).
Al igual que en el README se indica "daily_deaths_avg6" cuando en los datos la columna se denomina como "daily_deaths_avg7".

Saludos.

**Comment by numeroteca** [comment]
Gracias por informar.

> Os informo que tanto en los datos por CCAA como por provincias, la columna "intensive_care_per_1000000" (Casos UCI por 100.000 habitantes) debería de ser "intensive_care_per_100000" (le sobra un 0).

De momento no corregiremos el error para no romper los scripts de los reutilizadores. Lo dejamos apuntado para cuando abordemos este tipo de probleams históricos. Los datos que contiene sí están correctos, pero no su etiqueta.

> Al igual que en el README se indica "daily_deaths_avg6" cuando en los datos la columna se denomina como "daily_deaths_avg7".
Corregido. El error viene de cuando empezamos a calcular medias escogimos 6 en vez de 7 días.
