### ISSUE TITLE
Error en fecha de una fila

### ISSUE THREAD

**Issue by hmeleiro** [montera34/escovid19data#31]
He detectado un error en la file 7310 de [este csv](https://raw.githubusercontent.com/montera34/escovid19data/master/data/output/covid19-ccaa-spain_consolidated.csv). La fecha consta como 2022-01-13, me imagino que será 2021.

Un saludo. Gracias por el curro.

**Comment by numeroteca** [comment]
Tiene que ver con un dato erróneo de las vacunaciones. Ya está corregido en la serie pero no en el original de vacunaciones, @mharias nos contará de donde sale ese 2022, que es quien se encarga de los datos de vacunaciones.

**Comment by mharias** [comment]
Hola, disculpad que no lo detectara.. efectivamente es un fallo en la serie original, en este [fichero](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Informe_Comunicacion_20210113.ods). He corregido en dato en el csv, y lo comento en un wiki especifico que abriré para llevar control de cambios. Saludos

**Comment by mharias** [comment]
Si autorizáis cierro el issue..
saludos

**Comment by numeroteca** [comment]
Ok al cierre, pon antes el link a la página de la wiki.
