### ISSUE TITLE
Tabla interactiva para en Septiembre

### ISSUE THREAD

**Issue by pierreganty** [montera34/escovid19data#42]
Hola,

como indica el pantallazo, la tabla en formato interactiva por zonas basicas de salud en Madrid no va mas alla de Septiembre.

 <img width="511" alt="image" src="https://user-images.githubusercontent.com/2111160/142999004-8c76e3ff-918e-4546-b2ce-9721800c21f8.png">

No he comprobado se el problema se repite en otras tablas.

Estoy usando Firefox 94 en MacOS.

Gracias por su importante trabajo,
Pierre.

**Comment by puzzle72** [comment]
Hola, Pierre:

Pues hemos revisado el problema, y parece que lo tenemos resuelto. A partir
de las 1:00am del miércoles (o sea, en unos minutos desde que escribimos
esto), los datos, actualizados (salen todos los martes) deberían estar ya
disponibles.

Gracias a ti por tu interés en nuestra tarea,

Escovid19data

**Comment by numeroteca** [comment]
El problema era que por un retoque de los encabezados de las tablas se suprimía el 0 de de los meses de enero a septiembre de 2021 (quedando 21-9-29 en vez de 21-09-29) y eso hacía que alfabéticamente apareciera 21-10-06 antes que 21-9-29. Esto es, las fechas aparecían pero en orden equivocado.
Ya disponibles en https://lab.montera34.com/covid19-r/reports/madrid-escovid19data.html
Gracias por avisar.
