### ISSUE TITLE
You pushed a file with git conflicts

### ISSUE THREAD

**Issue by pierreganty** [montera34/escovid19data#43]
The picture shows it all.

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/2111160/144711139-5cd78593-726b-4a1d-867c-3df437169079.png">

Thank you for the great work.

**Comment by numeroteca** [comment]
Thanks for reporting. It's fixed now! (in the repository where we generate it https://code.montera34.com/numeroteca/covid19).
