### ISSUE TITLE
Málaga debe ir con tilde (para el script de hospitalizados de Andalucía)

### ISSUE THREAD

**Issue by numeroteca** [montera34/escovid19data#6]
"Málaga" aparece sin tilde en el CSV generado. 
Lo he corregido en el procesado que une todos los daos, pero mejor que esté correcto en el archivo csv generado. 
Script que lo genera: https://github.com/montera34/escovid19data/blob/master/analysis/descarga_andalucia.py
¡Gracias!

**Comment by congosto** [comment]
Corregido! subido script y datos
